version: "3.9"

services:
  rabbitmq:
    container_name: 'gotoeventsbot-rabbit'
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - gotoeventsbot-network

  postgres:
    container_name: gotoeventsbot-postgres
    image: "postgres:16-alpine"
    restart: unless-stopped
    environment:
      - POSTGRES_DB=gotoeventsbot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gotoeventsbot-network

volumes:
  postgres_data: {}

networks:
  gotoeventsbot-network:
    driver: bridge
